### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by AregGevorgyan** [plastuchino/reportsforlaylnc#1]
- About us should be on a seperate page so people can easily go back, there is currently no way to go back to the homepage other than reloading the website
- You should avoid telling people to log in with studentvue, just tell them to make an account and a password
- signup did not work for me at all
- Try implementing more features to the sign in to the sign up like password requirements and make sure you are storing password correctly (hashed, salt, pepper)

**Comment by plastuchino** [comment]
1) yeah the aboutus is just a placeholder for now but im going to make it the terms of service.

2)signing up with studentvue is the only reliable way i can confirm someone is an mcps student.

3)did u signup with mobile or on pc? What error did it give u? Did u provide valid student credentials

4)your password for laylnc is your studentvue password so im using the same password requirements mcps has

5) passwords are salted and peppered and their are encrypted using bcrypt. No one not even myself can see your plain text password
